/**
 * FILE: reminderService.js
 * PURPOSE: Handle all reminder-related business logic
 * DESCRIPTION: Create automatic reminders for payment cycles (pre-payment 5 days before, overdue after start date)
 */

const mongoose = require('mongoose');
const Notification = require('../../models/Notification');
const PaymentCycle = require('../../models/PaymentCycle');
const User = require('../../models/User');

/**
 * Create a pre-payment reminder (5 days before payment cycle starts)
 * @param {String} studentId - Student object ID
 * @param {Object} paymentCycle - PaymentCycle document
 * @returns {Object} Created Notification
 */
exports.createPrePaymentReminder = async (studentId, paymentCycle) => {
  try {
    // Don't create duplicate pre-payment reminders
    const existingReminder = await Notification.findOne({
      userId: studentId,
      type: 'payment_pre_payment',
      paymentCycleId: paymentCycle._id,
    });

    if (existingReminder) {
      console.log('⏭️  Pre-payment reminder already exists for cycle:', paymentCycle.cycleNumber);
      return null;
    }

    const startDate = new Date(paymentCycle.startDate);
    const formattedStartDate = startDate.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const reminder = new Notification({
      userId: new mongoose.Types.ObjectId(studentId),
      type: 'payment_pre_payment',
      title: '🔔 Payment Window Opening Soon',
      message: `Your payment for cycle ${paymentCycle.cycleNumber} will open on ${formattedStartDate}. Prepare your payment slip now!`,
      reminderType: 'pre_payment',
      autoGenerated: true,
      paymentCycleId: paymentCycle._id,
      cycleNumber: paymentCycle.cycleNumber,
      isRead: false,
      createdAt: new Date(),
    });

    const saved = await reminder.save();
    console.log('✅ Pre-payment reminder created for student:', studentId, 'Cycle:', paymentCycle.cycleNumber);
    return saved;
  } catch (error) {
    console.error('❌ Error creating pre-payment reminder:', error.message);
    throw error;
  }
};

/**
 * Create an overdue reminder (after payment cycle start date)
 * @param {String} studentId - Student object ID
 * @param {Object} paymentCycle - PaymentCycle document
 * @returns {Object} Created Notification
 */
exports.createOverdueReminder = async (studentId, paymentCycle) => {
  try {
    // Don't create duplicate overdue reminders
    const existingReminder = await Notification.findOne({
      userId: studentId,
      type: 'payment_overdue_reminder',
      paymentCycleId: paymentCycle._id,
    });

    if (existingReminder) {
      console.log('⏭️  Overdue reminder already exists for cycle:', paymentCycle.cycleNumber);
      return null;
    }

    const dueDate = new Date(paymentCycle.dueDate);
    const formattedDueDate = dueDate.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    const reminder = new Notification({
      userId: new mongoose.Types.ObjectId(studentId),
      type: 'payment_overdue_reminder',
      title: '⚠️ Payment Window Open - Action Required',
      message: `Your payment for cycle ${paymentCycle.cycleNumber} is now open. Submit your payment by ${formattedDueDate} to avoid penalties.`,
      reminderType: 'overdue',
      autoGenerated: true,
      paymentCycleId: paymentCycle._id,
      cycleNumber: paymentCycle.cycleNumber,
      isRead: false,
      createdAt: new Date(),
    });

    const saved = await reminder.save();
    console.log('✅ Overdue reminder created for student:', studentId, 'Cycle:', paymentCycle.cycleNumber);
    return saved;
  } catch (error) {
    console.error('❌ Error creating overdue reminder:', error.message);
    throw error;
  }
};

/**
 * Generate reminders for all active payment cycles based on dates
 * Pre-payment: 5 days before start date
 * Overdue: After start date (payment window open)
 * @returns {Object} Summary of created reminders
 */
exports.generateAllReminders = async () => {
  try {
    console.log('🔄 Starting reminder generation for all active payment cycles...');

    const today = new Date();
    today.setUTCHours(0, 0, 0, 0); // Midnight UTC

    // Get all active payment cycles
    const activeCycles = await PaymentCycle.find({ isActive: true })
      .populate('studentId', '_id email fullName')
      .sort({ startDate: 1 });

    console.log('📋 Found active cycles:', activeCycles.length);

    let prePaymentCount = 0;
    let overdueCount = 0;
    const results = [];

    for (const cycle of activeCycles) {
      const startDate = new Date(cycle.startDate);
      startDate.setUTCHours(0, 0, 0, 0); // Midnight UTC

      const dueDate = new Date(cycle.dueDate);
      dueDate.setUTCHours(0, 0, 0, 0); // Midnight UTC

      const fiveDaysBeforeStart = new Date(startDate);
      fiveDaysBeforeStart.setUTCDate(fiveDaysBeforeStart.getUTCDate() - 5);

      const studentId = cycle.studentId._id.toString();

      // Check if today is 5 days before start date (pre-payment reminder)
      if (today.getTime() === fiveDaysBeforeStart.getTime()) {
        console.log(`📅 Creating pre-payment reminder for student ${studentId}, Cycle ${cycle.cycleNumber}`);
        const result = await exports.createPrePaymentReminder(studentId, cycle);
        if (result) {
          prePaymentCount++;
          results.push({
            type: 'pre_payment',
            studentId,
            cycleNumber: cycle.cycleNumber,
            notificationId: result._id,
          });
        }
      }

      // Check if today is after start date (overdue/active reminder)
      if (today.getTime() > startDate.getTime() && today.getTime() <= dueDate.getTime()) {
        console.log(`📅 Creating overdue reminder for student ${studentId}, Cycle ${cycle.cycleNumber}`);
        const result = await exports.createOverdueReminder(studentId, cycle);
        if (result) {
          overdueCount++;
          results.push({
            type: 'overdue',
            studentId,
            cycleNumber: cycle.cycleNumber,
            notificationId: result._id,
          });
        }
      }
    }

    const summary = {
      success: true,
      totalCyclesProcessed: activeCycles.length,
      prePaymentRemindersCreated: prePaymentCount,
      overdueRemindersCreated: overdueCount,
      totalRemindersCreated: prePaymentCount + overdueCount,
      results,
      timestamp: new Date(),
    };

    console.log('✅ Reminder generation complete:', summary);
    return summary;
  } catch (error) {
    console.error('❌ Error generating reminders:', error.message);
    throw error;
  }
};

/**
 * Test-only function: Create a specific reminder type for the current user
 * Used for testing without waiting for actual dates
 * @param {String} userId - User ID to create reminder for
 * @param {String} reminderType - 'pre_payment' or 'overdue'
 * @returns {Object} Created Notification
 */
exports.createTestReminder = async (userId, reminderType) => {
  try {
    console.log(`🧪 Creating test ${reminderType} reminder for user:`, userId);

    // Get most recent active payment cycle for this user
    const paymentCycle = await PaymentCycle.findOne({
      studentId: new mongoose.Types.ObjectId(userId),
      isActive: true,
    }).sort({ startDate: -1 });

    if (!paymentCycle) {
      throw new Error('No active payment cycle found for this user');
    }

    let notification;

    if (reminderType === 'pre_payment') {
      notification = await exports.createPrePaymentReminder(userId, paymentCycle);
    } else if (reminderType === 'overdue') {
      notification = await exports.createOverdueReminder(userId, paymentCycle);
    } else {
      throw new Error('Invalid reminder type. Must be "pre_payment" or "overdue"');
    }

    if (!notification) {
      throw new Error('Reminder already exists');
    }

    return notification;
  } catch (error) {
    console.error('❌ Error creating test reminder:', error.message);
    throw error;
  }
};

/**
 * Clean up old reminders that are older than 30 days
 * @returns {Object} Summary of deleted reminders
 */
exports.cleanupOldReminders = async () => {
  try {
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const result = await Notification.deleteMany({
      autoGenerated: true,
      type: { $in: ['payment_pre_payment', 'payment_overdue_reminder'] },
      createdAt: { $lt: thirtyDaysAgo },
    });

    console.log('🧹 Cleanup complete. Removed old reminders:', result.deletedCount);

    return {
      success: true,
      deletedCount: result.deletedCount,
      olderThan: thirtyDaysAgo,
    };
  } catch (error) {
    console.error('❌ Error cleaning up reminders:', error.message);
    throw error;
  }
};
